version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgrespassword
    ports:
      - "5455:5432"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /home/node/app/node_modules
      - ./api:/home/node/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=crime_alert_app
      - PGPASSWORD=postgrespassword
      - PGPORT=5432
    ports:
      - "5000:5000"
  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app
    environment:
      - WDS_SOCKET_PORT=0
