apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: josefvivas/crime-alert-server
          ports:
            - containerPort: 5000
          ##insert varables of database here
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgressecret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgressecret
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgressecret
                  key: database
            - name: DB_HOST
              value: "localhost"
            - name: DB_PORT
              value: "5432"
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.28.0 # make sure the use the latest version
          command:
            - "/cloud_sql_proxy"
            - "-log_debug_stdout"
            - "-instances=crime-alerts-356219:us-central1:crime-app-postgres=tcp:5432"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: postgres
              mountPath: /secrets/
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
      volumes:
        - name: postgres
          secret:
            secretName: postgres
